import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar2";
import { MusicPlayer } from "@/components/Player";
import { ScrollArea } from "@/components/ui/scroll-area";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider
          style={{
            "--sidebar-width": "16rem",
            "--sidebar-width-mobile": "16rem",
            "--sidebar-width-icon": "5rem",
          }}
        >
          <AppSidebar className="mx-auto" />

          <main className="flex flex-col flex-grow px-6">
            <nav>
              <div className="flex">
                <div>MurMur</div>
                <SidebarTrigger />
              </div>
            </nav>
            <ScrollArea className="flex-grow">{children}</ScrollArea>
            <MusicPlayer />
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
